### ISSUE TITLE
Minecraft screen stuck on Encrypting...

### ISSUE THREAD

**Issue by seahorse1seahorse** [barneygale/quarry#154]
So I set up a Paper server that works. I can connect to it and it works perfectly. (I disabled online mode because I have TLauncher).
I set the port for the Paper server 12345.
My server.properties file looks like this:

> #Minecraft server properties
#Mon May 02 17:53:56 BRT 2022
enable-jmx-monitoring=false
rcon.port=25575
level-seed=
enable-command-block=false
gamemode=survival
enable-query=false
generator-settings={}
level-name=world
motd=A Minecraft Server
query.port=25565
pvp=true
generate-structures=true
difficulty=easy
network-compression-threshold=256
max-tick-time=60000
require-resource-pack=false
max-players=20
use-native-transport=true
online-mode=false
enable-status=true
allow-flight=false
broadcast-rcon-to-ops=true
view-distance=10
resource-pack-prompt=
server-ip=
allow-nether=true
server-port=12345
enable-rcon=false
sync-chunk-writes=true
cracked=true
op-permission-level=4
prevent-proxy-connections=false
hide-online-players=false
resource-pack=
entity-broadcast-range-percentage=100
simulation-distance=10
rcon.password=
player-idle-timeout=0
force-gamemode=false
debug=false
rate-limit=0
hardcore=false
white-list=false
broadcast-console-to-ops=true
spawn-npcs=true
spawn-animals=true
function-permission-level=2
level-type=default
text-filtering-config=
spawn-monsters=true
enforce-whitelist=false
resource-pack-sha1=
spawn-protection=16
max-world-size=29999984

So I tried to set up the proxy_hide_chat.py file like this:
`python3 proxy_hide_chat.py -q 12345`
The I try to connect to the local ip 127.0.0.1 (with Minecraft) There is no output. The screen in Minecraft is stuck on Encrypting... (after a while I get 'Timed Out')

When I try the same command with sudo I get:

> Traceback (most recent call last):
  File "/home/username/MCproxy/quarry/examples/proxy_hide_chat.py", line 9, in <module>
    from quarry.net.proxy import DownstreamFactory, Bridge
  File "/usr/local/lib/python3.10/dist-packages/quarry/net/proxy.py", line 4, in <module>
    from quarry.net.server import ServerFactory, ServerProtocol
  File "/usr/local/lib/python3.10/dist-packages/quarry/net/server.py", line 3, in <module>
    from cached_property import cached_property
ModuleNotFoundError: No module named 'cached_property'

When I try to install bitstring with `pip3 install bitstring` I get:

> Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: bitstring in /home/username/.local/lib/python3.10/site-packages (3.1.9)

The same happens with proxy_hide_chat.py or any other .py file from quarry/examples/ (I get the No module named 'bitstring' error)

If someone finds the solution, please give me detailed steps, I am new to Java. Thank you!

**Comment by koliwbr** [comment]
Using `sudo` is not necessary, ports above 1024 are available for unprivileged  users.
First try to connect to Minecraft without query. 
In server.propertis you change Minecraft port. Try on standard port. If it work, set port to `12345` and try connecting to `localhost:12345`

**Comment by Tuury** [comment]
I had the same problem . you have to set 
`factory.online_mode = False`

hope it helps :)

**Comment by seahorse1seahorse** [comment]
> I had the same problem . you have to set `factory.online_mode = False`
> 
> hope it helps :)

I have to put this in the Paper server.properties file?

**Comment by koliwbr** [comment]
> I have to put this in the Paper server.properties file? It didn't work for me.

In downstream proxy config if you using cracked minecraft account

**Comment by Tuury** [comment]
> 

yes in the proxy config . not in the properties file.

**Comment by seahorse1seahorse** [comment]
Unlock this secure message.

[Proton](https://proton.me/)

You have received an encrypted email from
***@***.***

[Learn more about password-protected emails](https://proton.me/support/password-protected-emails)

Expiry date
Monday May 30th 2022 at 09:03:42 GMT

Password hint
None

[Unlock message](https://mail.proton.me/eo/FAUcsRbz4y5KLvhmjz-SUmJ3_pm14o6VBjXtuVd628InpbYtts0ZAaachqsuik4CVdUZiYK_4JkLy1Th-7ST-s6QmqrgELwF9QMCwh76fzk=)

Please contact the sender if you have any trouble opening this email.

Want to send secure messages? Protect your privacy with a free [Proton account](https://proton.me/pricing).

Proton Mail is the world’s leading end-to-end encrypted email service, used by millions of people and businesses to secure their messages.

© 2022 Proton AG Switzerland

[Logos of Proton Mail, Proton Calendar, Proton Drive, Proton VPN]
