### ISSUE TITLE
Can't log into online-mode server while using offline profile

### ISSUE THREAD

**Issue by seahorse1seahorse** [barneygale/quarry#159]
Trying to connect to a minecraft server and getting this error:

> Can't log into online-mode server while using offline profile
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/quarry/net/protocol.py", line 245, in data_received
    self.packet_received(buff, name)
  File "/home/user/.local/lib/python3.10/site-packages/quarry/net/protocol.py", line 267, in packet_received
    dispatched = self.dispatch((name,), buff)
  File "/home/user/.local/lib/python3.10/site-packages/quarry/net/protocol.py", line 26, in dispatch
    handler(buff)
  File "/home/user/.local/lib/python3.10/site-packages/quarry/net/client.py", line 153, in packet_login_encryption_request
    raise ProtocolError("Can't log into online-mode server while using"
quarry.net.protocol.ProtocolError: Can't log into online-mode server while using offline profile

**Comment by davidawesome02** [comment]
Is your server in online mode?
If you are making a client which it seams you are, you have to use online mode profile to join


If you are using a proxy, try this `factory.online_mode = False` from [https://github.com/barneygale/quarry/issues/152](url)

 look here [https://github.com/barneygale/quarry/issues/135](url) and  look here [https://github.com/barneygale/quarry/pull/140](url) for moded ver with support for Microsoft login
