### ISSUE TITLE
no attribute 'resolve'

### ISSUE THREAD

**Issue by aaps** [barneygale/quarry#18]
Traceback (most recent call last):
  File "./proxy_recorder.py", line 3, in <module>
    from quarry.net.proxy import DownstreamFactory
  File "/usr/local/lib/python2.7/dist-packages/quarry/net/proxy.py", line 3, in <module>
    from quarry.net.protocol import PacketDispatcher
  File "/usr/local/lib/python2.7/dist-packages/quarry/net/protocol.py", line 7, in <module>
    from quarry.utils.crypto import Cipher
  File "/usr/local/lib/python2.7/dist-packages/quarry/utils/crypto.py", line 10, in <module>
    backend = default_backend()
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/__init__.py", line 35, in default_backend
    _default_backend = MultiBackend(_available_backends())
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/__init__.py", line 22, in _available_backends
    "cryptography.backends"
AttributeError: 'EntryPoint' object has no attribute 'resolve'

I wonder when this did happend, had to upgrade quarry since minecraft did an upgrade as well.
This was the result !

**Comment by aaps** [comment]
this might be something i did wrong since 2.3 release is not working as well.
still dont know what !

**Comment by aaps** [comment]
so we have this:
https://github.com/pyca/cryptography/issues/2853
https://github.com/airbnb/caravel/issues/252
and
https://github.com/pyca/cryptography/issues/2838

not an issue of quarry at all !

till cryptography 1.3 will work ?

**Comment by aaps** [comment]
should the setup.py work this way, that it doesnt install quarry from a clone and a setup.py install ?
that way i could test easyer and faster.
Perhaps i could extend the tests ?

**Comment by barneygale** [comment]
Works for me. Your links suggest this is an issue with your setuptools installation being too old.

**Comment by aaps** [comment]
you where right setup tools was too old, reinstalled python to fix that one !
