### ISSUE TITLE
Examples issues 

### ISSUE THREAD

**Issue by virus-rpi** [barneygale/quarry#181]
If i try to run the examle proxy it gives me that errror:
     
Traceback (most recent call last):
  File "C:\Users\n\AppData\Local\Programs\Python\Python39\lib\site-packages\twisted\internet\tcp.py", line 1334, in startListening
    skt.bind(addr)
OSError: [WinError 10049] The requested address is invalid in this context

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\proxy.py", line 109, in <module>
    main(sys.argv[1:])
  File "D:\Python\proxy.py", line 103, in main
    factory.listen(args.listen_host, args.listen_port)
  File "C:\Users\n\AppData\Local\Programs\Python\Python39\lib\site-packages\quarry\net\server.py", line 350, in listen
    reactor.listenTCP(port, self, interface=host)
  File "C:\Users\n\AppData\Local\Programs\Python\Python39\lib\site-packages\twisted\internet\posixbase.py", line 565, in listenTCP
    p.startListening()
  File "C:\Users\n\AppData\Local\Programs\Python\Python39\lib\site-packages\twisted\internet\tcp.py", line 1336, in startListening
    raise CannotListenError(self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on 93.186.205.153:25565: [WinError 10049] The requested address is invalid in this context

**Comment by davidawesome02** [comment]
Please send code it seams your address for opening was incorrect.

**Comment by virus-rpi** [comment]
I have found my mistake: I confused the ip address of the minecraft server with the one I connect to.
