### ISSUE TITLE
fcntl not found

### ISSUE THREAD

**Issue by ArtyuiCraft** [barneygale/quarry#186]
so when  i try to install it with pip i get this error:
`ModuleNotFoundError: No module named 'fcntl'`

here is the whole log when running the command:
`
C:\Windows\System32>pip install quarry
Collecting quarry
  Using cached quarry-1.9.4.tar.gz (66 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'test_requires'
        warnings.warn(msg)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\lisa Phoelich\AppData\Local\Temp\pip-install-3mw8jw44\quarry_2689535b006f40c7ab2175af17ad4d49\setup.py", line 3, in <module>
          setup(
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\distutils\core.py", line 108, in setup
          _setup_distribution = dist = klass(attrs)
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\dist.py", line 453, in __init__
          _Distribution.__init__(
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 292, in __init__
          self.finalize_options()
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\dist.py", line 830, in finalize_options
          for ep in sorted(loaded, key=by_order):
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\dist.py", line 829, in <lambda>
          loaded = map(lambda e: e.load(), filtered)
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\site-packages\pkg_resources\__init__.py", line 2450, in load
          return self.resolve()
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\site-packages\pkg_resources\__init__.py", line 2456, in resolve
          module = __import__(self.module_name, fromlist=['__name__'], level=0)
        File "C:\Users\lisa Phoelich\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\py2app\build_app.py", line 37, in <module>
          from py2app.create_appbundle import create_appbundle
        File "C:\Users\lisa Phoelich\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\py2app\create_appbundle.py", line 9, in <module>
          from py2app.util import make_exec, makedirs, mergecopy, mergetree, skipscm
        File "C:\Users\lisa Phoelich\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\py2app\util.py", line 5, in <module>
          import fcntl
      ModuleNotFoundError: No module named 'fcntl'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

C:\Windows\System32>`

i have googled it but it just says it doesn't work on windows but i saw people using this on windows so how can i fix this issue.

**Comment by davidawesome02** [comment]
try to install 
```pip3 install fcntl```
also its a bug not in this but in this library:
```py2app```
