### ISSUE TITLE
Messager not working

### ISSUE THREAD

**Issue by ashdawngary** [barneygale/quarry#36]
Hi, 

Im not sure if im a noob at this, but i ran python client_messenger.py on a test server.  This connection was made and i saw chat.  Since i ran it as just "python client_messenger.py", I couldnt find a way to send text to stdin.   I then tried piping strings from files but then this happened

Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/process.py", line 280, in doRead
    return fdesc.readFromFD(self.fd, self.dataReceived)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/fdesc.py", line 94, in readFromFD
    callback(output)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/process.py", line 283, in dataReceived
    self.proc.childDataReceived(self.name, data)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/_posixstdio.py", line 77, in childDataReceived
    self.protocol.dataReceived(data)
  File "/usr/lib/python2.7/dist-packages/twisted/protocols/basic.py", line 571, in dataReceived
    why = self.lineReceived(line)
  File "client.py", line 22, in lineReceived
    self.minecraft_protocol.send_chat(line.decode(self.in_encoding))
exceptions.TypeError: decode() argument 1 must be string, not None

I did "python client_messenger.py <<< string", but the same thing occured.  Could you tell me how exactly to run this?  I am out of ideas

**Comment by TiberiumN** [comment]
offtop:
just use python 3 and don't bother with encodings

**Comment by ashdawngary** [comment]
ok python3 works too, but I still cannot figure out on how to send in data.  If i type in "stdin"(where input() recieves data from or raw_input in 2.7), then it ignores it and keeps running.  If i try piping it it either says "Unhandled error in defered " or it also ignores it.  Any ideas on how to enter in data into "stdin"

**Comment by barneygale** [comment]
Does this fix it for you? 0ce9cd7c623e68c2a4018a82c03091ac5e6e74dd

**Comment by ashdawngary** [comment]
yes sort of

**Comment by barneygale** [comment]
Sort of?

**Comment by ashdawngary** [comment]
sometimes i get an" unhandeled error in defered "(and the async part of the program dies with no return), but if i restart it a few times it goes away.  I suspect that it is a problem on the server which crashes the program, not something on this end.
