### ISSUE TITLE
quarry.net.protocol.ProtocolError: No name known for packet: (5, 'status', 'upstream', 0)

### ISSUE THREAD

**Issue by undefinedvalue0103** [barneygale/quarry#60]
Hello, I'm tried to run some examples from /examples/ directory on Minecraft 1.7.10, but I got an error:

```
AuthProtocol{127.0.0.1} | ERROR | No name known for packet: (5, 'status', 'upstream', 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/quarry/net/protocol.py", line 206, in get_packet_name
    return packets.packet_names[key]
KeyError: (5, 'status', 'upstream', 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/quarry/net/protocol.py", line 242, in data_received
    name = self.get_packet_name(buff.unpack_varint())
  File "/usr/local/lib/python3.6/dist-packages/quarry/net/protocol.py", line 208, in get_packet_name
    raise ProtocolError("No name known for packet: %s" % (key,))
quarry.net.protocol.ProtocolError: No name known for packet: (5, 'status', 'upstream', 0)
```

Quarry not supports status requests?

BTW 1.10.2 works fine.

**Comment by barneygale** [comment]
Seemingly 1.7.6 through 1.7.10 don't have support. I'm not sure how I missed them though - will look into it!
