### ISSUE TITLE
Unknown protocol version

### ISSUE THREAD

**Issue by anton-bozhina** [barneygale/quarry#61]
Try to use server_downtime.py and other examples but everytime in game get error, in python some time. Use 1.14.3 game version, launch via official launcher.

```
DowntimeProtocol{127.0.0.1} | ERROR | No name known for packet: (490, 'status', 'upstream', 0)
Traceback (most recent call last):
  File "F:\Coding\Projects\McServerController\venv\lib\site-packages\quarry\net\protocol.py", line 206, in get_packet_name
    return packets.packet_names[key]
KeyError: (490, 'status', 'upstream', 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Coding\Projects\McServerController\venv\lib\site-packages\quarry\net\protocol.py", line 242, in data_received
    name = self.get_packet_name(buff.unpack_varint())
  File "F:\Coding\Projects\McServerController\venv\lib\site-packages\quarry\net\protocol.py", line 208, in get_packet_name
    raise ProtocolError("No name known for packet: %s" % (key,))
quarry.net.protocol.ProtocolError: No name known for packet: (490, 'status', 'upstream', 0)
DowntimeProtocol{192.168.1.111} | ERROR | No name known for packet: (490, 'status', 'upstream', 0)
Traceback (most recent call last):
  File "F:\Coding\Projects\McServerController\venv\lib\site-packages\quarry\net\protocol.py", line 206, in get_packet_name
    return packets.packet_names[key]
KeyError: (490, 'status', 'upstream', 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Coding\Projects\McServerController\venv\lib\site-packages\quarry\net\protocol.py", line 242, in data_received
    name = self.get_packet_name(buff.unpack_varint())
  File "F:\Coding\Projects\McServerController\venv\lib\site-packages\quarry\net\protocol.py", line 208, in get_packet_name
    raise ProtocolError("No name known for packet: %s" % (key,))
quarry.net.protocol.ProtocolError: No name known for packet: (490, 'status', 'upstream', 0)
```

**Comment by barneygale** [comment]
Try using the latest version from git:

    pip install -e git+https://github.com/barneygale/quarry.git

I'll make a pypi release ASAP.
